pipeline {
    agent any

    tools {
        jdk 'JDK25'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/your-repository/sample-maven-project.git'
            }
        }

        stage('Build') {
            steps {
                withMaven {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                withMaven {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                withMaven {
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
    }
}